#!/bin/bash

# Variables related to AWS kinesis stream
aws_kinesis_stream_name="<stream_name>"
aws_region=us-east-1

# AWS secret and access key pair, generated by the user for specific services.
aws_access_key=<your-aws-access-key>
aws_secret_key=<your-aws-secret-key>

# Launching the surveillance script
gst-launch-1.0 nvarguscamerasrc ! 'video/x-raw(memory:NVMM), format=NV12, width=640, height=480' ! nvv4l2h264enc insert-sps-pps=true ! h264parse ! kvssink stream-name="${aws_kinesis_stream_name}" access-key="${aws_access_key}" secret-key="${aws_sercret_key}" aws-region="${aws_region}"
